/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_berkeley_boinc_jni_Boinc */

#ifndef _Included_edu_berkeley_boinc_jni_Boinc
#define _Included_edu_berkeley_boinc_jni_Boinc
#ifdef __cplusplus
extern "C" {
#endif
#undef edu_berkeley_boinc_jni_Boinc_serialVersionUID
#define edu_berkeley_boinc_jni_Boinc_serialVersionUID 1LL
/*
 * Class:     edu_berkeley_boinc_jni_Boinc
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_berkeley_boinc_jni_Boinc_init__
  (JNIEnv *, jobject);

/*
 * Class:     edu_berkeley_boinc_jni_Boinc
 * Method:    init
 * Signature: (ZZZZZZZZ)V
 */
JNIEXPORT void JNICALL Java_edu_berkeley_boinc_jni_Boinc_init__ZZZZZZZZ
  (JNIEnv *, jobject, jboolean, jboolean, jboolean, jboolean, jboolean, jboolean, jboolean, jboolean);

/*
 * Class:     edu_berkeley_boinc_jni_Boinc
 * Method:    finish
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_berkeley_boinc_jni_Boinc_finish__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_berkeley_boinc_jni_Boinc
 * Method:    finish
 * Signature: (ILjava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_edu_berkeley_boinc_jni_Boinc_finish__ILjava_lang_String_2Z
  (JNIEnv *, jobject, jint, jstring, jboolean);

/*
 * Class:     edu_berkeley_boinc_jni_Boinc
 * Method:    resolveFileName
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_berkeley_boinc_jni_Boinc_resolveFileName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     edu_berkeley_boinc_jni_Boinc
 * Method:    getApplicationInitData
 * Signature: (Ledu/berkeley/boinc/jni/ApplicationInitData;)I
 */
JNIEXPORT jint JNICALL Java_edu_berkeley_boinc_jni_Boinc_getApplicationInitData
  (JNIEnv *, jobject, jobject);

/*
 * Class:     edu_berkeley_boinc_jni_Boinc
 * Method:    parseInitDataFile
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_berkeley_boinc_jni_Boinc_parseInitDataFile
  (JNIEnv *, jobject);

/*
 * Class:     edu_berkeley_boinc_jni_Boinc
 * Method:    sendTrickleUp
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_edu_berkeley_boinc_jni_Boinc_sendTrickleUp
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     edu_berkeley_boinc_jni_Boinc
 * Method:    setMinCheckpointPeriod
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_edu_berkeley_boinc_jni_Boinc_setMinCheckpointPeriod
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_berkeley_boinc_jni_Boinc
 * Method:    checkpointCompleted
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_berkeley_boinc_jni_Boinc_checkpointCompleted
  (JNIEnv *, jobject);

/*
 * Class:     edu_berkeley_boinc_jni_Boinc
 * Method:    reportFractionDone
 * Signature: (D)I
 */
JNIEXPORT jint JNICALL Java_edu_berkeley_boinc_jni_Boinc_reportFractionDone
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     edu_berkeley_boinc_jni_Boinc
 * Method:    suspendOtherActivities
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_berkeley_boinc_jni_Boinc_suspendOtherActivities
  (JNIEnv *, jobject);

/*
 * Class:     edu_berkeley_boinc_jni_Boinc
 * Method:    resumeOtherActivities
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_berkeley_boinc_jni_Boinc_resumeOtherActivities
  (JNIEnv *, jobject);

/*
 * Class:     edu_berkeley_boinc_jni_Boinc
 * Method:    reportAppStatus
 * Signature: (DDD)I
 */
JNIEXPORT jint JNICALL Java_edu_berkeley_boinc_jni_Boinc_reportAppStatus
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     edu_berkeley_boinc_jni_Boinc
 * Method:    isTimeToCheckpoint
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_edu_berkeley_boinc_jni_Boinc_isTimeToCheckpoint
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
