/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_berkeley_boinc_api_bridge_BasicAPI */

#ifndef _Included_edu_berkeley_boinc_api_bridge_BasicAPI
#define _Included_edu_berkeley_boinc_api_bridge_BasicAPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_berkeley_boinc_api_bridge_BasicAPI
 * Method:    boinc_init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_berkeley_boinc_api_bridge_BasicAPI_boinc_1init
  (JNIEnv *, jclass);

/*
 * Class:     edu_berkeley_boinc_api_bridge_BasicAPI
 * Method:    boinc_init_options
 * Signature: (Ledu/berkeley/boinc/api/bridge/BOINC_OPTIONS;)I
 */
JNIEXPORT jint JNICALL Java_edu_berkeley_boinc_api_bridge_BasicAPI_boinc_1init_1options
  (JNIEnv *, jclass, jobject);

/*
 * Class:     edu_berkeley_boinc_api_bridge_BasicAPI
 * Method:    boinc_options_defaults
 * Signature: (Ledu/berkeley/boinc/api/bridge/BOINC_OPTIONS;)I
 */
JNIEXPORT jint JNICALL Java_edu_berkeley_boinc_api_bridge_BasicAPI_boinc_1options_1defaults
  (JNIEnv *, jclass, jobject);

/*
 * Class:     edu_berkeley_boinc_api_bridge_BasicAPI
 * Method:    boinc_finish
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_edu_berkeley_boinc_api_bridge_BasicAPI_boinc_1finish
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_berkeley_boinc_api_bridge_BasicAPI
 * Method:    boinc_finish_message
 * Signature: (ILjava/lang/String;Z)I
 */
JNIEXPORT jint JNICALL Java_edu_berkeley_boinc_api_bridge_BasicAPI_boinc_1finish_1message
  (JNIEnv *, jclass, jint, jstring, jboolean);

/*
 * Class:     edu_berkeley_boinc_api_bridge_BasicAPI
 * Method:    boinc_resolve_filename
 * Signature: (Ljava/lang/String;Ljava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_edu_berkeley_boinc_api_bridge_BasicAPI_boinc_1resolve_1filename
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     edu_berkeley_boinc_api_bridge_BasicAPI
 * Method:    boinc_time_to_checkpoint
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_berkeley_boinc_api_bridge_BasicAPI_boinc_1time_1to_1checkpoint
  (JNIEnv *, jclass);

/*
 * Class:     edu_berkeley_boinc_api_bridge_BasicAPI
 * Method:    boinc_checkpoint_completed
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_berkeley_boinc_api_bridge_BasicAPI_boinc_1checkpoint_1completed
  (JNIEnv *, jclass);

/*
 * Class:     edu_berkeley_boinc_api_bridge_BasicAPI
 * Method:    boinc_begin_critical_section
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_berkeley_boinc_api_bridge_BasicAPI_boinc_1begin_1critical_1section
  (JNIEnv *, jclass);

/*
 * Class:     edu_berkeley_boinc_api_bridge_BasicAPI
 * Method:    boinc_end_critical_section
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_berkeley_boinc_api_bridge_BasicAPI_boinc_1end_1critical_1section
  (JNIEnv *, jclass);

/*
 * Class:     edu_berkeley_boinc_api_bridge_BasicAPI
 * Method:    boinc_fraction_done
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_edu_berkeley_boinc_api_bridge_BasicAPI_boinc_1fraction_1done
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     edu_berkeley_boinc_api_bridge_BasicAPI
 * Method:    boinc_wu_cpu_time
 * Signature: (Ljava/lang/Double;)I
 */
JNIEXPORT jint JNICALL Java_edu_berkeley_boinc_api_bridge_BasicAPI_boinc_1wu_1cpu_1time
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
